/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class EditarProveedores extends javax.swing.JFrame{

    Timer timer = new Timer (1000, new ActionListener (){
        @Override
        public void actionPerformed(ActionEvent e){
            int s = 0;
            if(s == 0){
                avisopresionar.setText("PRESIONE ENTER PARA ACTUALIZAR");
                timer.stop();
            }
            s++;
        }
    });
    boolean pguionnit = true, sguionnit = false, havebusiness = false;
    DefaultComboBoxModel precomboproviders;
    /**
     * Creates new form EditarProveedores
     * @param provider
     * @param comboproviders
     */
    public EditarProveedores(DefaultTableModel provider, DefaultComboBoxModel comboproviders) {
        initComponents();
        this.setResizable(false);
        try{
            proveedores.setModel(provider);
            providers.setModel(comboproviders);
        }catch(java.lang.IllegalArgumentException vacío){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        providers = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        proveedores = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PLNombre = new javax.swing.JLabel();
        pnombres = new javax.swing.JTextField();
        PLApellidos = new javax.swing.JLabel();
        papellidos = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        astericoNI = new javax.swing.JLabel();
        PLNIToCedula = new javax.swing.JComboBox<>();
        pnitocedula = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        PLDireccion = new javax.swing.JLabel();
        pdireccion = new javax.swing.JTextField();
        PLEmpresa = new javax.swing.JLabel();
        pempresa = new javax.swing.JTextField();
        PLTelefono = new javax.swing.JLabel();
        ptelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        avisopresionar = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();

        providers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editar proveedores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedores"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT/Cédula", "Nombre", "Apellidos", "Dirección/Dirección de empresa", "Empresa", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(proveedores);
        if (proveedores.getColumnModel().getColumnCount() > 0) {
            proveedores.getColumnModel().getColumn(0).setResizable(false);
            proveedores.getColumnModel().getColumn(1).setResizable(false);
            proveedores.getColumnModel().getColumn(2).setResizable(false);
            proveedores.getColumnModel().getColumn(3).setResizable(false);
            proveedores.getColumnModel().getColumn(4).setResizable(false);
            proveedores.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar);

        jLabel2.setText("  ");
        jPanel3.add(jLabel2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1);

        jLabel3.setText("  ");
        jPanel3.add(jLabel3);

        jLabel1.setText("Buscar por NIT o Cédula: ");
        jPanel3.add(jLabel1);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });
        jPanel3.add(search);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel3.add(buscar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("                 ");
        jPanel5.add(jLabel6);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new java.awt.GridLayout(3, 2));

        PLNombre.setText("*Nombres:");
        jPanel6.add(PLNombre);

        pnombres.setEnabled(false);
        pnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnombresKeyTyped(evt);
            }
        });
        jPanel6.add(pnombres);

        PLApellidos.setText("*Apellidos:");
        jPanel6.add(PLApellidos);

        papellidos.setEnabled(false);
        papellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                papellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                papellidosKeyTyped(evt);
            }
        });
        jPanel6.add(papellidos);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        astericoNI.setText("*");
        jPanel15.add(astericoNI);

        PLNIToCedula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT", "Cédula" }));
        PLNIToCedula.setBorder(null);
        PLNIToCedula.setEnabled(false);
        PLNIToCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLNIToCedulaActionPerformed(evt);
            }
        });
        jPanel15.add(PLNIToCedula);

        jPanel6.add(jPanel15);

        pnitocedula.setEnabled(false);
        pnitocedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnitocedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnitocedulaKeyTyped(evt);
            }
        });
        jPanel6.add(pnitocedula);

        jPanel4.add(jPanel6);

        jPanel8.setLayout(new java.awt.GridLayout(3, 2));

        PLDireccion.setText("*Dirección de la empresa:");
        jPanel8.add(PLDireccion);

        pdireccion.setEnabled(false);
        pdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pdireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pdireccionKeyTyped(evt);
            }
        });
        jPanel8.add(pdireccion);

        PLEmpresa.setText("*Empresa:");
        jPanel8.add(PLEmpresa);

        pempresa.setEnabled(false);
        pempresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pempresaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pempresaKeyTyped(evt);
            }
        });
        jPanel8.add(pempresa);

        PLTelefono.setText("*Teléfono:");
        jPanel8.add(PLTelefono);

        ptelefono.setEnabled(false);
        ptelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ptelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ptelefonoKeyTyped(evt);
            }
        });
        jPanel8.add(ptelefono);

        jPanel4.add(jPanel8);

        jPanel5.add(jPanel4);

        jLabel7.setText("                 ");
        jPanel5.add(jLabel7);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        avisopresionar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        avisopresionar.setForeground(new java.awt.Color(0, 0, 153));
        avisopresionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisopresionar.setText("PRESIONE ENTER PARA ACTUALIZAR");
        jPanel7.add(avisopresionar);

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(cerrar);

        jPanel1.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLNIToCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLNIToCedulaActionPerformed
        if (PLNIToCedula.getSelectedItem().equals("Cédula")) {
            PLEmpresa.setEnabled(false);
            pempresa.setEnabled(false);
            PLDireccion.setText("*Dirección:");
            pempresa.setText("");
            pnitocedula.setText("");
            pnitocedula.grabFocus();
            havebusiness = true;
        } else if (PLNIToCedula.getSelectedItem().equals("NIT")) {
            PLEmpresa.setEnabled(true);
            pempresa.setEnabled(true);
            PLDireccion.setText("*Dirección de la empresa:");
            pnitocedula.setText("");
            pnitocedula.grabFocus();
            havebusiness = false;
            pguionnit = false;
        }
    }//GEN-LAST:event_PLNIToCedulaActionPerformed

    private void ptelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptelefonoKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || ptelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_ptelefonoKeyTyped

    private void pnitocedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnitocedulaKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || pnitocedula.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_pnitocedulaKeyTyped

    private void papellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papellidosKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || papellidos.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_papellidosKeyTyped

    private void pnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnombresKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || pnombres.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_pnombresKeyTyped

    private void proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresMouseClicked
        if (proveedores.getSelectedRowCount() > 0) {
            int indices = proveedores.getRowCount();
            for (int i = 0; i < indices; i++) {
                if (proveedores.getSelectedRow() == i) {
                    if(isNIT(proveedores.getValueAt(proveedores.getSelectedRow(), 0).toString())){
                        PLNIToCedula.setSelectedItem("NIT");
                        pnitocedula.setText(proveedores.getValueAt(i, 0).toString());
                        PLEmpresa.setEnabled(true);
                        pempresa.setEnabled(true);
                        pempresa.setText(proveedores.getValueAt(i, 4).toString());
                        pguionnit = true;
                    }else{
                        PLNIToCedula.setSelectedItem("Cédula");
                        pnitocedula.setText(proveedores.getValueAt(i, 0).toString());
                        PLEmpresa.setEnabled(false);
                        pempresa.setEnabled(false);
                        pempresa.setText("");
                    }
                    pnombres.setText(proveedores.getValueAt(i, 1).toString());
                    papellidos.setText(proveedores.getValueAt(i, 2).toString());
                    pdireccion.setText(proveedores.getValueAt(i, 3).toString());
                    ptelefono.setText(proveedores.getValueAt(i, 5).toString());
                    havebusiness = true;
                    habilitar();
                    break;
                }
            }
        }
    }//GEN-LAST:event_proveedoresMouseClicked

    private void pnombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnombresKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(pnombres.getText() != null && !"".equals(pnombres.getText())){
                for(int i=0;i<proveedores.getRowCount();i++){
                    if(proveedores.getSelectedRow() == i){
                        precomboproviders = (DefaultComboBoxModel) providers.getModel();
                        precomboproviders.removeElementAt(i);
                        precomboproviders.insertElementAt(modificarComboBox(), i);
                        providers.setModel(precomboproviders);
                        proveedores.setValueAt(pnombres.getText(),i, 1);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de nombre.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }                
        }
    }//GEN-LAST:event_pnombresKeyPressed

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        if(!Character.isDigit(evt.getKeyChar()) || search.getText().length() >= 12){
            evt.consume();
        }
    }//GEN-LAST:event_searchKeyTyped

    private void pdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pdireccionKeyTyped
        if(pdireccion.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_pdireccionKeyTyped

    private void pempresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pempresaKeyTyped
        if(pempresa.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_pempresaKeyTyped

    private void pnitocedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnitocedulaKeyPressed
        if("NIT".equals(PLNIToCedula.getSelectedItem().toString())){
            switch (evt.getKeyCode()) {
                case KeyEvent.VK_ENTER:
                    try{
                    if(pnitocedula.getText().substring(pnitocedula.getText().length()-1, pnitocedula.getText().length()).contains("-") || !pnitocedula.getText().contains("-")){
                        JOptionPane.showMessageDialog(null, "Digite correctamente el campo de NIT.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                        evt.consume();
                    }else{
                        for(int i=0;i<proveedores.getRowCount();i++){
                            if(proveedores.getSelectedRow() == i){
                                precomboproviders = (DefaultComboBoxModel) providers.getModel();
                                precomboproviders.removeElementAt(i);
                                precomboproviders.insertElementAt(modificarComboBox(), i);
                                proveedores.setValueAt(pnitocedula.getText(),i, 0);
                                if(!havebusiness){
                                    proveedores.setValueAt("",i, 4);
                                    pempresa.grabFocus();
                                }                            
                                providers.setModel(precomboproviders);
                                break;
                                }
                            }
                        avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                        timer.start();
                    }
                    }catch(java.lang.StringIndexOutOfBoundsException minusone){
                        JOptionPane.showMessageDialog(null, "Digite correctamente el campo de NIT.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                        evt.consume();
                    }   break;
                case 45:
                    if (pnitocedula.getText() == null || "".equals(pnitocedula.getText()) && pguionnit == false) {
                        evt.consume();
                    } else if ((pnitocedula.getText() != null || !"".equals(pnitocedula.getText())) && pguionnit == false) {
                        pnitocedula.setText(pnitocedula.getText() + "-");
                        pguionnit = true;
                    }   break;
                case KeyEvent.VK_BACK_SPACE:
                    try{
                        String cadena = pnitocedula.getText().substring(0, pnitocedula.getText().length()-1);
                        pguionnit = cadena.contains("-");
                    }catch(java.lang.StringIndexOutOfBoundsException minusone){
                        pguionnit = false;
                    }   break;                 
                default:
                    break;
            }
        }else if("Cédula".equals(PLNIToCedula.getSelectedItem().toString())){
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(pnitocedula.getText() == null || "".equals(pnitocedula.getText())){
                    JOptionPane.showMessageDialog(null, "Digite correctamente el campo de Cédula.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                    evt.consume();
                }else{
                    for(int i=0;i<proveedores.getRowCount();i++){
                        if(proveedores.getSelectedRow() == i){
                            precomboproviders = (DefaultComboBoxModel) providers.getModel();
                            precomboproviders.removeElementAt(i);
                            precomboproviders.insertElementAt(modificarComboBox(), i);
                            proveedores.setValueAt(pnitocedula.getText(),i, 0);
                            proveedores.setValueAt("",i, 4);
                            providers.setModel(precomboproviders);
                            havebusiness = true;
                            break;
                        }
                    }
                    avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                    timer.start();
                }
            }
        }
    }//GEN-LAST:event_pnitocedulaKeyPressed

    private void papellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papellidosKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(papellidos.getText() != null && !"".equals(papellidos.getText())){
                for(int i=0;i<proveedores.getRowCount();i++){
                    if(proveedores.getSelectedRow() == i){
                        precomboproviders = (DefaultComboBoxModel) providers.getModel();
                        precomboproviders.removeElementAt(i);
                        precomboproviders.insertElementAt(modificarComboBox(), i);
                        proveedores.setValueAt(papellidos.getText(),i, 2);
                        providers.setModel(precomboproviders);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de apellidos.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_papellidosKeyPressed

    private void pdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pdireccionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(pdireccion.getText() != null && !"".equals(pdireccion.getText())){
                for(int i=0;i<proveedores.getRowCount();i++){
                    if(proveedores.getSelectedRow() == i){
                        precomboproviders = (DefaultComboBoxModel) providers.getModel();
                        precomboproviders.removeElementAt(i);
                        precomboproviders.insertElementAt(modificarComboBox(), i);
                        proveedores.setValueAt(pdireccion.getText(),i, 3);
                        providers.setModel(precomboproviders);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de dirección.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }  
        }
    }//GEN-LAST:event_pdireccionKeyPressed

    private void pempresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pempresaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(pempresa.getText() != null && !"".equals(pempresa.getText())){
                for(int i=0;i<proveedores.getRowCount();i++){
                    if(proveedores.getSelectedRow() == i){
                        precomboproviders = (DefaultComboBoxModel) providers.getModel();
                        precomboproviders.removeElementAt(i);
                        precomboproviders.insertElementAt(modificarComboBox(), i);
                        proveedores.setValueAt(pempresa.getText(),i, 4);
                        providers.setModel(precomboproviders);
                        havebusiness = true;
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de empresa.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_pempresaKeyPressed

    private void ptelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptelefonoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(ptelefono.getText() != null && !"".equals(ptelefono.getText())){
                for(int i=0;i<proveedores.getRowCount();i++){
                    if(proveedores.getSelectedRow() == i){
                        precomboproviders = (DefaultComboBoxModel) providers.getModel();
                        precomboproviders.removeElementAt(i);
                        precomboproviders.insertElementAt(modificarComboBox(), i);
                        proveedores.setValueAt(ptelefono.getText(),i, 5);
                        providers.setModel(precomboproviders);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de teléfono.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_ptelefonoKeyPressed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        DefaultTableModel proveedor = (DefaultTableModel) proveedores.getModel();

        if (proveedores.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Antes de eliminar proveedores, tiene que seleccionarlos.", "Seleccione los proveedores a eliminar", JOptionPane.WARNING_MESSAGE);
        } else {
            int[] indices = proveedores.getSelectedRows();
            for (int i : indices) {
                if (proveedores.getSelectedRow() == i) {
                    precomboproviders = (DefaultComboBoxModel) providers.getModel();
                    proveedor.removeRow(i);
                    precomboproviders.removeElementAt(i);
                }
            }
            proveedores.setModel(proveedor);
            providers.setModel(precomboproviders);
            JOptionPane.showMessageDialog(null, "El proveedor ha sido eliminado exitosamente.", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        boolean encontrado = false;
        if(search.getText() != null && !"".equals(search.getText())){
            
                for(int i=0;i<proveedores.getRowCount();i++){
                    if(proveedores.getValueAt(i, 0).toString().equals(search.getText())){
                        proveedores.changeSelection(i, 0, false, false);
                        if(!proveedores.getValueAt(i, 0).toString().contains("-")){
                            PLNIToCedula.setSelectedItem("Cédula");
                            PLEmpresa.setEnabled(false);
                            pempresa.setEnabled(false);
                            pempresa.setText("");
                        }else{
                            PLNIToCedula.setSelectedItem("NIT");
                            PLEmpresa.setEnabled(true);
                            pempresa.setEnabled(true);
                            pempresa.setText(proveedores.getValueAt(i, 4).toString());
                        }
                        pnitocedula.setText(proveedores.getValueAt(i, 0).toString());                      
                        pnombres.setText(proveedores.getValueAt(i, 1).toString());
                        papellidos.setText(proveedores.getValueAt(i, 2).toString());
                        pdireccion.setText(proveedores.getValueAt(i, 3).toString());
                        ptelefono.setText(proveedores.getValueAt(i, 5).toString());
                        habilitar();
                        encontrado = true;
                        break;
                    }
                }
                if(!encontrado){
                    JOptionPane.showMessageDialog(null, "No se pudo encontrar el proveedor.", "No encontrado", JOptionPane.WARNING_MESSAGE);
                }         
        }else{
            JOptionPane.showMessageDialog(null, "Digite el NIT o cédula del proveedor a buscar.", "Vacío", JOptionPane.WARNING_MESSAGE);
        }
                
    }//GEN-LAST:event_buscarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        boolean verificarempresanula = false;
        for(int i=0;i<proveedores.getRowCount();i++){
            if(proveedores.getValueAt(i, 0).toString().contains("-") && (proveedores.getValueAt(i, 4).toString() == null || "".equals(proveedores.getValueAt(i, 4).toString()))){
                verificarempresanula = true;
                break;
            }
        }
        if(!verificarempresanula){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Digite la empresa del proveedor", "Falta la empresa", JOptionPane.WARNING_MESSAGE);            
        }        
    }//GEN-LAST:event_cerrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        boolean verificarempresanula = false;
        for(int i=0;i<proveedores.getRowCount();i++){
            if(proveedores.getValueAt(i, 0).toString().contains("-") && (proveedores.getValueAt(i, 4).toString() == null || "".equals(proveedores.getValueAt(i, 4).toString()))){
                verificarempresanula = true;
                break;
            }
        }
        if(!verificarempresanula){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Digite la empresa del proveedor", "Falta la empresa", JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(800, 350);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Icon.png"));
            setIconImage(icon);
            setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        switch (evt.getKeyCode()) {
                case 45:
                    if (search.getText() == null || "".equals(search.getText()) && sguionnit == false) {
                        evt.consume();
                    } else if ((search.getText() != null || !"".equals(search.getText())) && sguionnit == false) {
                        search.setText(search.getText() + "-");
                        sguionnit = true;
                    }   break;
                case KeyEvent.VK_BACK_SPACE:
                    try{
                        String cadena = search.getText().substring(0, search.getText().length()-1);
                        sguionnit = cadena.contains("-");
                    }catch(java.lang.StringIndexOutOfBoundsException minusone){
                        sguionnit = false;
                    }   break;                 
                default:
                    try{
                        String cadena = search.getText();
                        sguionnit = cadena.contains("-");
                    }catch(java.lang.StringIndexOutOfBoundsException minusone){
                        sguionnit = false;
                    }
                    break;
        }
    }//GEN-LAST:event_searchKeyPressed

    private String modificarComboBox() {
        String cadena = "";
        if("NIT".equals(PLNIToCedula.getSelectedItem().toString())){
            cadena = "NIT: " + pnitocedula.getText() + " - " + pempresa.getText() + " - " + pnombres.getText() + " " + papellidos.getText();
        }else if("Cédula".equals(PLNIToCedula.getSelectedItem().toString())){
            cadena = "Cédula: " + pnitocedula.getText() + " - " + pnombres.getText() + " " + papellidos.getText();
        }
        return cadena;
    }

    private boolean isNIT(String isNITorCedula) {
        return isNITorCedula.contains("-");
    }
    
    private void habilitar(){
        pnombres.setEnabled(true);
        papellidos.setEnabled(true);
        pdireccion.setEnabled(true);
        pnitocedula.setEnabled(true);
        PLNIToCedula.setEnabled(true);
        ptelefono.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PLApellidos;
    private javax.swing.JLabel PLDireccion;
    private javax.swing.JLabel PLEmpresa;
    private javax.swing.JComboBox<String> PLNIToCedula;
    private javax.swing.JLabel PLNombre;
    private javax.swing.JLabel PLTelefono;
    private javax.swing.JLabel astericoNI;
    private javax.swing.JLabel avisopresionar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField papellidos;
    private javax.swing.JTextField pdireccion;
    private javax.swing.JTextField pempresa;
    private javax.swing.JTextField pnitocedula;
    private javax.swing.JTextField pnombres;
    private javax.swing.JTable proveedores;
    private javax.swing.JComboBox<String> providers;
    private javax.swing.JTextField ptelefono;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables

}
