/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class EditarClientes extends javax.swing.JFrame{

    Timer timer = new Timer (1000, new ActionListener (){
        @Override
        public void actionPerformed(ActionEvent e){
            int s = 0;
            if(s == 0){
                avisopresionar.setText("PRESIONE ENTER PARA ACTUALIZAR");
                timer.stop();
            }
            s++;
        }
    });
    
    /**
     * Creates new form EditarProveedores
     * @param client
     */
    public EditarClientes(DefaultTableModel client) {
        initComponents();
        this.setResizable(false);
        try{
            clientes.setModel(client);
        }catch(java.lang.IllegalArgumentException vacío){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PLNombre = new javax.swing.JLabel();
        cnombres = new javax.swing.JTextField();
        PLApellidos = new javax.swing.JLabel();
        capellidos = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        astericoNI = new javax.swing.JLabel();
        PLCedula = new javax.swing.JLabel();
        ccedula = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        PLDireccion = new javax.swing.JLabel();
        cdireccion = new javax.swing.JTextField();
        PLEmpresa = new javax.swing.JLabel();
        cempresa = new javax.swing.JTextField();
        PLTelefono = new javax.swing.JLabel();
        ctelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        avisopresionar = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar);

        jLabel2.setText("  ");
        jPanel3.add(jLabel2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1);

        jLabel3.setText("  ");
        jPanel3.add(jLabel3);

        jLabel1.setText("Buscar por Cédula: ");
        jPanel3.add(jLabel1);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });
        jPanel3.add(search);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel3.add(buscar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Apellidos", "Dirección", "Lugar de trabajo", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(clientes);
        if (clientes.getColumnModel().getColumnCount() > 0) {
            clientes.getColumnModel().getColumn(0).setResizable(false);
            clientes.getColumnModel().getColumn(1).setResizable(false);
            clientes.getColumnModel().getColumn(2).setResizable(false);
            clientes.getColumnModel().getColumn(3).setResizable(false);
            clientes.getColumnModel().getColumn(4).setResizable(false);
            clientes.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("                 ");
        jPanel5.add(jLabel6);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new java.awt.GridLayout(3, 2));

        PLNombre.setText("*Nombres:");
        jPanel6.add(PLNombre);

        cnombres.setEnabled(false);
        cnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnombresKeyTyped(evt);
            }
        });
        jPanel6.add(cnombres);

        PLApellidos.setText("*Apellidos:");
        jPanel6.add(PLApellidos);

        capellidos.setEnabled(false);
        capellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                capellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                capellidosKeyTyped(evt);
            }
        });
        jPanel6.add(capellidos);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        astericoNI.setText("*");
        jPanel15.add(astericoNI);

        PLCedula.setText("Cédula:");
        jPanel15.add(PLCedula);

        jPanel6.add(jPanel15);

        ccedula.setEnabled(false);
        ccedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ccedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccedulaKeyTyped(evt);
            }
        });
        jPanel6.add(ccedula);

        jPanel4.add(jPanel6);

        jPanel8.setLayout(new java.awt.GridLayout(3, 2));

        PLDireccion.setText("*Dirección:");
        jPanel8.add(PLDireccion);

        cdireccion.setEnabled(false);
        cdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cdireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cdireccionKeyTyped(evt);
            }
        });
        jPanel8.add(cdireccion);

        PLEmpresa.setText("Lugar de trabajo:");
        jPanel8.add(PLEmpresa);

        cempresa.setEnabled(false);
        cempresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cempresaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cempresaKeyTyped(evt);
            }
        });
        jPanel8.add(cempresa);

        PLTelefono.setText("*Teléfono:");
        jPanel8.add(PLTelefono);

        ctelefono.setEnabled(false);
        ctelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ctelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctelefonoKeyTyped(evt);
            }
        });
        jPanel8.add(ctelefono);

        jPanel4.add(jPanel8);

        jPanel5.add(jPanel4);

        jLabel7.setText("                 ");
        jPanel5.add(jLabel7);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        avisopresionar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        avisopresionar.setForeground(new java.awt.Color(0, 0, 153));
        avisopresionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisopresionar.setText("PRESIONE ENTER PARA ACTUALIZAR");
        jPanel7.add(avisopresionar);

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(cerrar);

        jPanel1.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctelefonoKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || ctelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_ctelefonoKeyTyped

    private void capellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capellidosKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || capellidos.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_capellidosKeyTyped

    private void cnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnombresKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || cnombres.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_cnombresKeyTyped

    private void cnombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnombresKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(cnombres.getText() != null && !"".equals(cnombres.getText())){
                for(int i=0;i<clientes.getRowCount();i++){
                    if(clientes.getSelectedRow() == i){
                        clientes.setValueAt(cnombres.getText(),i, 1);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de nombre.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }                
        }
    }//GEN-LAST:event_cnombresKeyPressed

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        if(!Character.isDigit(evt.getKeyChar()) || search.getText().length() >= 12){
            evt.consume();
        }
    }//GEN-LAST:event_searchKeyTyped

    private void cdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cdireccionKeyTyped
        if(cdireccion.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_cdireccionKeyTyped

    private void cempresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cempresaKeyTyped
        if(cempresa.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_cempresaKeyTyped

    private void capellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capellidosKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(capellidos.getText() != null && !"".equals(capellidos.getText())){
                for(int i=0;i<clientes.getRowCount();i++){
                    if(clientes.getSelectedRow() == i){
                        clientes.setValueAt(capellidos.getText(),i, 2);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de apellidos.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_capellidosKeyPressed

    private void cdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cdireccionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(cdireccion.getText() != null && !"".equals(cdireccion.getText())){
                for(int i=0;i<clientes.getRowCount();i++){
                    if(clientes.getSelectedRow() == i){
                        clientes.setValueAt(cdireccion.getText(),i, 3);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de dirección.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }  
        }
    }//GEN-LAST:event_cdireccionKeyPressed

    private void cempresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cempresaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

                for(int i=0;i<clientes.getRowCount();i++){
                    if(clientes.getSelectedRow() == i){
                        clientes.setValueAt(cempresa.getText(),i, 4);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
        }
    }//GEN-LAST:event_cempresaKeyPressed

    private void ctelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctelefonoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(ctelefono.getText() != null && !"".equals(ctelefono.getText())){
                for(int i=0;i<clientes.getRowCount();i++){
                    if(clientes.getSelectedRow() == i){
                        clientes.setValueAt(ctelefono.getText(),i, 5);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de teléfono.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_ctelefonoKeyPressed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        DefaultTableModel cliente = (DefaultTableModel) clientes.getModel();

        if (clientes.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Antes de eliminar proveedores, tiene que seleccionarlos.", "Seleccione los proveedores a eliminar", JOptionPane.WARNING_MESSAGE);
        } else {
            int[] indices = clientes.getSelectedRows();
            for (int i : indices) {
                if (clientes.getSelectedRow() == i) {
                    cliente.removeRow(i);
                }
            }
            clientes.setModel(cliente);
            JOptionPane.showMessageDialog(null, "El cliente ha sido eliminado exitosamente.", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        boolean encontrado = false;
        if(search.getText() != null && !"".equals(search.getText())){
            
                for(int i=0;i<clientes.getRowCount();i++){
                    if(clientes.getValueAt(i, 0).toString().equals(search.getText())){
                        clientes.changeSelection(i, 0, false, false);
                        cempresa.setText(clientes.getValueAt(i, 4).toString());
                        ccedula.setText(clientes.getValueAt(i, 0).toString());                      
                        cnombres.setText(clientes.getValueAt(i, 1).toString());
                        capellidos.setText(clientes.getValueAt(i, 2).toString());
                        cdireccion.setText(clientes.getValueAt(i, 3).toString());
                        ctelefono.setText(clientes.getValueAt(i, 5).toString());
                        encontrado = true;
                        habilitar();
                        break;
                    }
                }
                if(!encontrado){
                    JOptionPane.showMessageDialog(null, "No se pudo encontrar el cliente.", "No encontrado", JOptionPane.WARNING_MESSAGE);
                }         
        }else{
            JOptionPane.showMessageDialog(null, "Digite la cédula del cliente a buscar.", "Vacío", JOptionPane.WARNING_MESSAGE);
        }
                
    }//GEN-LAST:event_buscarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(800, 350);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Icon.png"));
            setIconImage(icon);
            setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseClicked
        if (clientes.getSelectedRowCount() > 0) {
            int indices = clientes.getRowCount();
            for (int i = 0; i < indices; i++) {
                if (clientes.getSelectedRow() == i) {
                    ccedula.setText(clientes.getValueAt(i, 0).toString());
                    cnombres.setText(clientes.getValueAt(i, 1).toString());
                    capellidos.setText(clientes.getValueAt(i, 2).toString());
                    cdireccion.setText(clientes.getValueAt(i, 3).toString());
                    cempresa.setText(clientes.getValueAt(i, 4).toString());
                    ctelefono.setText(clientes.getValueAt(i, 5).toString());
                    habilitar();
                    break;
                }
            }
        }
    }//GEN-LAST:event_clientesMouseClicked

    private void ccedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccedulaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            for(int i=0;i<clientes.getRowCount();i++){
                if(clientes.getSelectedRow() == i){
                    clientes.setValueAt(ccedula.getText(),i, 0);
                    break;
                }
            }
            avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
            timer.start();
        }
    }//GEN-LAST:event_ccedulaKeyPressed

    private void ccedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccedulaKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || ccedula.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_ccedulaKeyTyped

    private void habilitar(){
        cnombres.setEnabled(true);
        capellidos.setEnabled(true);
        cdireccion.setEnabled(true);
        ccedula.setEnabled(true);
        cempresa.setEnabled(true);
        ctelefono.setEnabled(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PLApellidos;
    private javax.swing.JLabel PLCedula;
    private javax.swing.JLabel PLDireccion;
    private javax.swing.JLabel PLEmpresa;
    private javax.swing.JLabel PLNombre;
    private javax.swing.JLabel PLTelefono;
    private javax.swing.JLabel astericoNI;
    private javax.swing.JLabel avisopresionar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField capellidos;
    private javax.swing.JTextField ccedula;
    private javax.swing.JTextField cdireccion;
    private javax.swing.JTextField cempresa;
    private javax.swing.JButton cerrar;
    private javax.swing.JTable clientes;
    private javax.swing.JTextField cnombres;
    private javax.swing.JTextField ctelefono;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables

}
