/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class EditarProductos extends javax.swing.JFrame{

    Timer timer = new Timer (1000, new ActionListener (){
        @Override
        public void actionPerformed(ActionEvent e){
            int s = 0;
            if(s == 0){
                avisopresionar.setText("PRESIONE ENTER PARA ACTUALIZAR");
                timer.stop();
            }
            s++;
        }
    });
    
    boolean iunitvaluepoint = false, cambiado = false;
    DefaultComboBoxModel precomboproviders;
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy hh:mm a");
    /**
     * Creates new form EditarProveedores
     * @param provider
     * @param parafacturacion
     * @param comboproviders
     */
    public EditarProductos(DefaultTableModel provider, DefaultTableModel parafacturacion, DefaultComboBoxModel comboproviders) {
        initComponents();
        this.setResizable(false);
        try{
            productos.setModel(provider);
            items.setModel(parafacturacion);
            providers.setModel(comboproviders);            
        }catch(java.lang.IllegalArgumentException vacío){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        items = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PLProducto = new javax.swing.JLabel();
        iproducto = new javax.swing.JTextField();
        PLCodigo = new javax.swing.JLabel();
        icodigo = new javax.swing.JTextField();
        PLProveedor = new javax.swing.JLabel();
        providers = new javax.swing.JComboBox<>();
        PLFecha = new javax.swing.JLabel();
        ifechaingreso = new javax.swing.JSpinner();
        PLCantidad = new javax.swing.JLabel();
        icantidad = new javax.swing.JTextField();
        PLCaducidad = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        icaducidad = new javax.swing.JSpinner();
        inotiene = new javax.swing.JComboBox<>();
        PLLote = new javax.swing.JLabel();
        ilote = new javax.swing.JTextField();
        PLClase = new javax.swing.JLabel();
        iclase = new javax.swing.JComboBox<>();
        PLINVIMA = new javax.swing.JLabel();
        iinvima = new javax.swing.JTextField();
        PLValUnit = new javax.swing.JLabel();
        ivalorunitario = new javax.swing.JTextField();
        PLiva = new javax.swing.JLabel();
        iiva = new javax.swing.JTextField();
        PLValTotal = new javax.swing.JLabel();
        ivalortotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        avisopresionar = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();

        items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Valor unitario", "IVA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(items);
        if (items.getColumnModel().getColumnCount() > 0) {
            items.getColumnModel().getColumn(0).setResizable(false);
            items.getColumnModel().getColumn(1).setResizable(false);
            items.getColumnModel().getColumn(2).setResizable(false);
            items.getColumnModel().getColumn(3).setResizable(false);
            items.getColumnModel().getColumn(4).setResizable(false);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar productos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar);

        jLabel2.setText("  ");
        jPanel3.add(jLabel2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1);

        jLabel3.setText("  ");
        jPanel3.add(jLabel3);

        jLabel1.setText("Buscar por código de producto: ");
        jPanel3.add(jLabel1);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });
        jPanel3.add(search);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel3.add(buscar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre del producto", "Cantidad", "Proveedor", "Fecha y hora de ingreso", "Fecha de caducidad", "Lote", "Clase de producto", "INVIMA", "Valor unitario", "IVA", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(productos);
        if (productos.getColumnModel().getColumnCount() > 0) {
            productos.getColumnModel().getColumn(0).setResizable(false);
            productos.getColumnModel().getColumn(1).setResizable(false);
            productos.getColumnModel().getColumn(2).setResizable(false);
            productos.getColumnModel().getColumn(3).setResizable(false);
            productos.getColumnModel().getColumn(4).setResizable(false);
            productos.getColumnModel().getColumn(5).setResizable(false);
            productos.getColumnModel().getColumn(6).setResizable(false);
            productos.getColumnModel().getColumn(7).setResizable(false);
            productos.getColumnModel().getColumn(8).setResizable(false);
            productos.getColumnModel().getColumn(9).setResizable(false);
            productos.getColumnModel().getColumn(10).setResizable(false);
            productos.getColumnModel().getColumn(11).setResizable(false);
        }

        jPanel2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("                 ");
        jPanel5.add(jLabel6);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new java.awt.GridLayout(12, 2, 0, 3));

        PLProducto.setText("*Nombre del producto:");
        jPanel6.add(PLProducto);

        iproducto.setEnabled(false);
        iproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iproductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iproductoKeyTyped(evt);
            }
        });
        jPanel6.add(iproducto);

        PLCodigo.setText("*Código:");
        jPanel6.add(PLCodigo);

        icodigo.setEnabled(false);
        icodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                icodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                icodigoKeyTyped(evt);
            }
        });
        jPanel6.add(icodigo);

        PLProveedor.setText("*Proveedor:");
        jPanel6.add(PLProveedor);

        providers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        providers.setEnabled(false);
        providers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providersActionPerformed(evt);
            }
        });
        jPanel6.add(providers);

        PLFecha.setText("*Fecha y hora de ingreso:");
        jPanel6.add(PLFecha);

        ifechaingreso.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1167627600000L), new java.util.Date(2114398800000L), java.util.Calendar.DAY_OF_MONTH));
        ifechaingreso.setEnabled(false);
        ifechaingreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ifechaingresoStateChanged(evt);
            }
        });
        jPanel6.add(ifechaingreso);

        PLCantidad.setText("*Cantidad:");
        jPanel6.add(PLCantidad);

        icantidad.setEnabled(false);
        icantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                icantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                icantidadKeyTyped(evt);
            }
        });
        jPanel6.add(icantidad);

        PLCaducidad.setText("*Fecha de caducidad:");
        jPanel6.add(PLCaducidad);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        icaducidad.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1483246800000L), new java.util.Date(2114398800000L), java.util.Calendar.DAY_OF_MONTH));
        icaducidad.setEnabled(false);
        icaducidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                icaducidadStateChanged(evt);
            }
        });
        jPanel9.add(icaducidad);

        inotiene.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                ", "Ninguna" }));
        inotiene.setEnabled(false);
        inotiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inotieneActionPerformed(evt);
            }
        });
        jPanel9.add(inotiene);

        jPanel6.add(jPanel9);

        PLLote.setText("*Lote:");
        jPanel6.add(PLLote);

        ilote.setEnabled(false);
        ilote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iloteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iloteKeyTyped(evt);
            }
        });
        jPanel6.add(ilote);

        PLClase.setText("*Clase de producto:");
        jPanel6.add(PLClase);

        iclase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos de aseo personal", "Productos de aseo para el hogar", "Medicamentos" }));
        iclase.setEnabled(false);
        iclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iclaseActionPerformed(evt);
            }
        });
        jPanel6.add(iclase);

        PLINVIMA.setText("*Registro sanitario:");
        jPanel6.add(PLINVIMA);

        iinvima.setEnabled(false);
        iinvima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iinvimaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iinvimaKeyTyped(evt);
            }
        });
        jPanel6.add(iinvima);

        PLValUnit.setText("*Valor unitario:");
        jPanel6.add(PLValUnit);

        ivalorunitario.setEnabled(false);
        ivalorunitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ivalorunitarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ivalorunitarioKeyTyped(evt);
            }
        });
        jPanel6.add(ivalorunitario);

        PLiva.setText("IVA:");
        jPanel6.add(PLiva);

        iiva.setEnabled(false);
        iiva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iivaKeyTyped(evt);
            }
        });
        jPanel6.add(iiva);

        PLValTotal.setText("Valor total:");
        jPanel6.add(PLValTotal);

        ivalortotal.setEnabled(false);
        jPanel6.add(ivalortotal);

        jPanel4.add(jPanel6);

        jPanel5.add(jPanel4);

        jLabel7.setText("                 ");
        jPanel5.add(jLabel7);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        avisopresionar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        avisopresionar.setForeground(new java.awt.Color(0, 0, 153));
        avisopresionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisopresionar.setText("PRESIONE ENTER PARA ACTUALIZAR");
        jPanel7.add(avisopresionar);

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(cerrar);

        jPanel1.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        if(search.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_searchKeyTyped

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        DefaultTableModel proveedor = (DefaultTableModel) productos.getModel();
        DefaultTableModel facturacion = (DefaultTableModel) items.getModel();

        if (productos.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Antes de eliminar productos, tiene que seleccionarlos.", "Seleccione los productos a eliminar", JOptionPane.WARNING_MESSAGE);
        } else {
            int[] indices = productos.getSelectedRows();
            for (int i : indices) {
                if (productos.getSelectedRow() == i) {
                    proveedor.removeRow(i);
                    facturacion.removeRow(i);
                }
            }
            productos.setModel(proveedor);
            items.setModel(facturacion);
            JOptionPane.showMessageDialog(null, "El producto ha sido eliminado exitosamente.", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        boolean encontrado = false;
        if(search.getText() != null && !"".equals(search.getText())){
            
                for(int i=0;i<productos.getRowCount();i++){
                    if(productos.getValueAt(i, 0).toString().equals(search.getText())){
                        try {
                            Date predate;
                            productos.changeSelection(i, 0, false, false);
                            iproducto.setText(productos.getValueAt(i, 1).toString());
                            icodigo.setText(productos.getValueAt(i, 0).toString());
                            icantidad.setText(productos.getValueAt(i, 2).toString());
                            providers.setSelectedItem(productos.getValueAt(i, 3).toString());
                            predate = formato.parse(productos.getValueAt(i, 4).toString());
                            ifechaingreso.setValue(predate);
                            if("Ninguna".equals(productos.getValueAt(i, 5).toString())){
                                inotiene.setSelectedItem(productos.getValueAt(i, 5).toString());
                            }else{
                                cambiado = true;
                                inotiene.setSelectedIndex(0);
                                predate = formato.parse(productos.getValueAt(i, 5).toString());
                                icaducidad.setValue(predate);
                                icaducidad.setEnabled(true);
                            }
                            ilote.setText(productos.getValueAt(i, 6).toString());
                            iclase.setSelectedItem(productos.getValueAt(i, 7).toString());
                            iinvima.setText(productos.getValueAt(i, 8).toString());
                            ivalorunitario.setText(productos.getValueAt(i, 9).toString());
                            iiva.setText(productos.getValueAt(i, 10).toString());
                            ivalortotal.setText(productos.getValueAt(i, 11).toString());
                            habilitar();
                            encontrado = true;
                            break;
                        } catch (ParseException ex) {
                            Logger.getLogger(EditarProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                if(!encontrado){
                    JOptionPane.showMessageDialog(null, "No se pudo encontrar el producto.", "No encontrado", JOptionPane.WARNING_MESSAGE);
                }         
        }else{
            JOptionPane.showMessageDialog(null, "Digite el código del producto a buscar.", "Vacío", JOptionPane.WARNING_MESSAGE);
        }
                
    }//GEN-LAST:event_buscarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(1300, 715);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Icon.png"));
            setIconImage(icon);
            setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void iinvimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iinvimaKeyTyped
        if(iinvima.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_iinvimaKeyTyped

    private void iivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iivaKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_iivaKeyTyped

    private void iloteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iloteKeyTyped
        if(ilote.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_iloteKeyTyped

    private void ivalorunitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivalorunitarioKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || "0".equals(ivalorunitario.getText()) || ivalorunitario.getText().length() >= 30) {
            evt.consume();
        } else if (icantidad.getText() != null && !"".equals(icantidad.getText())) {
            iiva.setText(String.valueOf((Double.parseDouble(ivalorunitario.getText() + evt.getKeyChar()) * Integer.parseInt(icantidad.getText())) * 0.19));
            ivalortotal.setText(String.valueOf((Double.parseDouble(ivalorunitario.getText() + evt.getKeyChar()) * Integer.parseInt(icantidad.getText())) + Double.parseDouble(iiva.getText())));
        }
    }//GEN-LAST:event_ivalorunitarioKeyTyped

    private void ivalorunitarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivalorunitarioKeyPressed
        switch (evt.getKeyCode()) {
            case 46:
                if (ivalorunitario.getText() == null || "".equals(ivalorunitario.getText()) && iunitvaluepoint == false) {
                    evt.consume();
                } else if ("0".equals(ivalorunitario.getText())) {
                    ivalorunitario.setText("0.");
                    iunitvaluepoint = true;
                } else if ((ivalorunitario.getText() != null || !"".equals(ivalorunitario.getText())) && iunitvaluepoint == false) {
                    ivalorunitario.setText(ivalorunitario.getText() + ".");
                    iunitvaluepoint = true;
                }   break;
            case 8:
                String ipuvalue;
                try{
                    ipuvalue = ivalorunitario.getText().substring(0, ivalorunitario.getText().length()-1);
                    iunitvaluepoint = ipuvalue.contains(".");
                }catch(java.lang.StringIndexOutOfBoundsException minusone){
                    ipuvalue = "";
                    iunitvaluepoint = false;
                }   if (icantidad.getText() != null && !"".equals(icantidad.getText()) && ivalorunitario.getText() != null && !"".equals(ivalorunitario.getText())) {
                    if ("".equals(ipuvalue)) {
                        iiva.setText("0.0");
                        ivalortotal.setText("0.0");
                    } else {
                        iiva.setText(String.valueOf((Double.parseDouble(ipuvalue) * Integer.parseInt(icantidad.getText())) * 0.19));
                        ivalortotal.setText(String.valueOf((Double.parseDouble(ipuvalue) * Integer.parseInt(icantidad.getText())) + Double.parseDouble(iiva.getText())));
                    }
                }   break;
            case KeyEvent.VK_ENTER:
                String havepoint;
                try{
                    havepoint = ivalorunitario.getText().substring(ivalorunitario.getText().length()-1, ivalorunitario.getText().length());
                }catch(java.lang.StringIndexOutOfBoundsException minusone){
                    havepoint = "";
                }   if(".".equals(havepoint) || "".equals(havepoint) || "0".equals(ivalorunitario.getText())){
                    JOptionPane.showMessageDialog(null, "Digite correctamente el campo de valor unitario.", havepoint, HEIGHT);
                } else {
                    for(int i=0;i<productos.getRowCount();i++){
                        if(i == productos.getSelectedRow()){
                            productos.setValueAt(ivalorunitario.getText(), i, 9);
                            productos.setValueAt(iiva.getText(), i, 10);
                            productos.setValueAt(ivalortotal.getText(), i, 11);
                            items.setValueAt(ivalorunitario.getText(), i, 3);
                            items.setValueAt(iiva.getText(), i, 4);
                            break;
                        }
                    }
                    avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                    timer.start();
                }   break;
            default:
                break;
        }
    }//GEN-LAST:event_ivalorunitarioKeyPressed

    private void inotieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inotieneActionPerformed
        if (inotiene.getSelectedItem() == "Ninguna") {
            icaducidad.setEnabled(false);
            for(int i=0;i<productos.getRowCount();i++){
                if(productos.getSelectedRow() == i){
                    productos.setValueAt(inotiene.getSelectedItem(),i, 5);
                    break;
                }
            }
            cambiado = false;
        } else if (!cambiado) {
            icaducidad.setEnabled(true);
            for(int i=0;i<productos.getRowCount();i++){
                if(productos.getSelectedRow() == i){
                    productos.setValueAt(formato.format(new Date()),i, 5);
                    icaducidad.setValue(new Date());
                    break;
                }
            }
        }
        avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
        timer.start();
    }//GEN-LAST:event_inotieneActionPerformed

    private void icantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icantidadKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || icantidad.getText().length() >= 20 || (evt.getKeyChar() == '0' && (icantidad.getText() == null || "".equals(icantidad.getText())))) {
            evt.consume();
        } else if (ivalorunitario.getText() != null && !"".equals(ivalorunitario.getText())) {
            iiva.setText(String.valueOf((Double.parseDouble(ivalorunitario.getText()) * Integer.parseInt(icantidad.getText() + evt.getKeyChar())) * 0.19));
            ivalortotal.setText(String.valueOf((Double.parseDouble(ivalorunitario.getText()) * Integer.parseInt(icantidad.getText() + evt.getKeyChar())) + Double.parseDouble(iiva.getText())));
        }
    }//GEN-LAST:event_icantidadKeyTyped

    private void icantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icantidadKeyPressed
        if (evt.getKeyCode() == 8) {
            if (ivalorunitario.getText() != null && !"".equals(ivalorunitario.getText()) && icantidad.getText() != null && !"".equals(icantidad.getText())) {
                String iprquantity;
                try{
                    iprquantity = ivalorunitario.getText().substring(0, ivalorunitario.getText().length()-1);
                }catch(java.lang.StringIndexOutOfBoundsException minusone){
                    iprquantity = "";
                }
                if ("".equals(iprquantity) || iprquantity == null) {
                    iiva.setText("0.0");
                    ivalortotal.setText("0.0");
                } else {
                    iiva.setText(String.valueOf((Double.parseDouble(ivalorunitario.getText()) * Integer.parseInt(iprquantity)) * 0.19));
                    ivalortotal.setText(String.valueOf((Double.parseDouble(ivalorunitario.getText()) * Integer.parseInt(iprquantity)) + Double.parseDouble(iiva.getText())));
                }
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(icantidad.getText() != null && !"".equals(icantidad.getText())){
                for(int i=0;i<productos.getRowCount();i++){
                    if(i == productos.getSelectedRow()){
                        productos.setValueAt(icantidad.getText(), i, 2);
                        productos.setValueAt(iiva.getText(), i, 10);
                        productos.setValueAt(ivalortotal.getText(), i, 11);
                        items.setValueAt(icantidad.getText(), i, 2);
                        items.setValueAt(iiva.getText(), i, 4);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");                
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo de cantidad", "Incorrecto", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_icantidadKeyPressed

    private void icodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icodigoKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || icodigo.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_icodigoKeyTyped

    private void icodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            boolean iscoderepeat = false;            
                
            if(icodigo.getText() != null && !"".equals(icodigo.getText())){
                for (int i = 0; i < productos.getRowCount(); i++) {
                    DefaultTableModel preproductos = (DefaultTableModel) productos.getModel();
                    preproductos.removeRow(productos.getSelectedRow());
                    if (icodigo.getText().equals(preproductos.getValueAt(i, 0).toString())) {
                        JOptionPane.showMessageDialog(null, "El código ingresado ya existe.", "Código", JOptionPane.ERROR_MESSAGE);
                        iscoderepeat = true;
                        break;
                    }
                }
                
                if(!iscoderepeat){
                    for(int i=0;i<productos.getRowCount();i++){
                        if(productos.getSelectedRow() == i){
                            productos.setValueAt(icodigo.getText(),i, 0);
                            break;
                        }
                    }
                    avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
                    timer.start();
                }else{
                    JOptionPane.showMessageDialog(null, "El código ingresado ya existe", "Repetido", JOptionPane.ERROR_MESSAGE);
                    evt.consume();
                }                    
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo del código", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_icodigoKeyPressed

    private void iproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iproductoKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || iproducto.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_iproductoKeyTyped

    private void iproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iproductoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(iproducto.getText() != null && !"".equals(iproducto.getText())){
                for(int i=0;i<productos.getRowCount();i++){
                    if(productos.getSelectedRow() == i){
                        productos.setValueAt(iproducto.getText(),i, 1);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo del nombre del producto.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_iproductoKeyPressed

    private void providersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providersActionPerformed
        for(int i=0;i<productos.getRowCount();i++){
            if(productos.getSelectedRow() == i){
                productos.setValueAt(providers.getSelectedItem(),i, 3);
                break;
            }
        }
        avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
        timer.start();
    }//GEN-LAST:event_providersActionPerformed

    private void productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseClicked
        if (productos.getSelectedRowCount() > 0) {
            int indices = productos.getRowCount();
            for (int i = 0; i < indices; i++) {
                if (productos.getSelectedRow() == i) {
                    try {
                        Date predate;
                        if(haveExpiration(productos.getValueAt(productos.getSelectedRow(), 5).toString())){
                            try {
                                cambiado = true;
                                inotiene.setSelectedIndex(0);                                
                                predate = formato.parse(productos.getValueAt(i, 5).toString());
                                icaducidad.setValue(predate);
                                icaducidad.setEnabled(true);
                            } catch (ParseException ex) {
                                Logger.getLogger(EditarProductos.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }else{
                            icaducidad.setEnabled(false);
                            inotiene.setSelectedItem("Ninguna");
                        }
                        iproducto.setText(productos.getValueAt(i, 1).toString());
                        icodigo.setText(productos.getValueAt(i, 0).toString());
                        icantidad.setText(productos.getValueAt(i, 2).toString());
                        providers.setSelectedItem(productos.getValueAt(i, 3).toString());
                        predate = formato.parse(productos.getValueAt(i, 4).toString());
                        ifechaingreso.setValue(predate);
                        ilote.setText(productos.getValueAt(i, 6).toString());
                        iclase.setSelectedItem(productos.getValueAt(i, 7).toString());
                        iinvima.setText(productos.getValueAt(i, 8).toString());
                        ivalorunitario.setText(productos.getValueAt(i, 9).toString());
                        iiva.setText(productos.getValueAt(i, 10).toString());
                        ivalortotal.setText(productos.getValueAt(i, 11).toString());
                        habilitar();
                        break;
                    } catch (ParseException ex) {
                        Logger.getLogger(EditarProductos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_productosMouseClicked

    private void iloteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iloteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(ilote.getText() != null && !"".equals(ilote.getText())){
                for(int i=0;i<productos.getRowCount();i++){
                    if(productos.getSelectedRow() == i){
                        productos.setValueAt(ilote.getText(),i, 6);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo del lote del producto.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_iloteKeyPressed

    private void iclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iclaseActionPerformed
        for(int i=0;i<productos.getRowCount();i++){
            if(productos.getSelectedRow() == i){
                productos.setValueAt(iclase.getSelectedItem(),i, 7);
                break;
            }
        }
        avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
        timer.start();
    }//GEN-LAST:event_iclaseActionPerformed

    private void iinvimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iinvimaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(iinvima.getText() != null && !"".equals(iinvima.getText())){
                for(int i=0;i<productos.getRowCount();i++){
                    if(productos.getSelectedRow() == i){
                        productos.setValueAt(iinvima.getText(),i, 8);
                        break;
                    }
                }
                avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
                timer.start();
            }else{
                JOptionPane.showMessageDialog(null, "Digite correctamente el campo del registro sanitario.", "Incorrecto", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_iinvimaKeyPressed

    private void ifechaingresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ifechaingresoStateChanged
            for(int i=0;i<productos.getRowCount();i++){
            if(productos.getSelectedRow() == i){
                productos.setValueAt(formato.format(ifechaingreso.getValue()),i, 4);
                break;
            }
        }
        avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
        timer.start();
    }//GEN-LAST:event_ifechaingresoStateChanged

    private void icaducidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_icaducidadStateChanged
            for(int i=0;i<productos.getRowCount();i++){
            if(productos.getSelectedRow() == i){
                productos.setValueAt(formato.format(icaducidad.getValue()),i, 5);
                break;
            }
            }
            avisopresionar.setText("ACTUALIZADO EXITOSAMENTE");
            timer.start();
    }//GEN-LAST:event_icaducidadStateChanged

    private boolean haveExpiration(String expiration){
        return !"Ninguna".equals(expiration);
    }
//    private String modificarComboBox() {
//        String cadena = "";
//        if("NIT".equals(PLNIToCedula.getSelectedItem().toString())){
//            cadena = "NIT: " + pnitocedula.getText() + " - " + pempresa.getText() + " - " + iproducto.getText() + " " + icodigo.getText();
//        }else if("Cédula".equals(PLNIToCedula.getSelectedItem().toString())){
//            cadena = "Cédula: " + pnitocedula.getText() + " - " + iproducto.getText() + " " + icodigo.getText();
//        }
//        return cadena;
//    }
    
    private void habilitar(){
        iproducto.setEnabled(true);
        icodigo.setEnabled(true);
        providers.setEnabled(true);
        ifechaingreso.setEnabled(true);
        icantidad.setEnabled(true);
        ilote.setEnabled(true);
        iclase.setEnabled(true);
        iinvima.setEnabled(true);
        ivalorunitario.setEnabled(true);
        inotiene.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PLCaducidad;
    private javax.swing.JLabel PLCantidad;
    private javax.swing.JLabel PLClase;
    private javax.swing.JLabel PLCodigo;
    private javax.swing.JLabel PLFecha;
    private javax.swing.JLabel PLINVIMA;
    private javax.swing.JLabel PLLote;
    private javax.swing.JLabel PLProducto;
    private javax.swing.JLabel PLProveedor;
    private javax.swing.JLabel PLValTotal;
    private javax.swing.JLabel PLValUnit;
    private javax.swing.JLabel PLiva;
    private javax.swing.JLabel avisopresionar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton eliminar;
    private javax.swing.JSpinner icaducidad;
    private javax.swing.JTextField icantidad;
    private javax.swing.JComboBox<String> iclase;
    private javax.swing.JTextField icodigo;
    private javax.swing.JSpinner ifechaingreso;
    private javax.swing.JTextField iinvima;
    private javax.swing.JTextField iiva;
    private javax.swing.JTextField ilote;
    private javax.swing.JComboBox<String> inotiene;
    private javax.swing.JTextField iproducto;
    private javax.swing.JTable items;
    private javax.swing.JTextField ivalortotal;
    private javax.swing.JTextField ivalorunitario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable productos;
    private javax.swing.JComboBox<String> providers;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables

}
